server:
  port: 33001
spring:
  profiles: 
    active: dev
  application:
    name: service-config-server
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-config-server
