server:
  port: 33001
spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dotterbear/service-repo-config
          username:
          password:
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-config-server
