server:
  port: 33001
spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/pqab-ms/repo-config.git
          username: config
          password: ENC(fgIzg8IOl+0Rf3Lg/yiPBhG23NHLRGHlRroer4AP/2M=)
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-config-server
