spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dotterbear/service-repo-config
          username:
          password:
eureka:
  instance:
    hostname: 127.0.0.1
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
